Feature/a 05 berichten gelezen markeren
Klantinteractie-Servicesysteem/KISS-frontend pull request #258
Opened 2022-08-30 08:13 UTC by lencodes

DRAFT.

2022-09-02 15:11 UTC, lencodes commented on src/features/werkbericht/service.ts
> -    const params: [string, string][] = [["orderby", "modified"]];
This was implemented, but I was told by the backend team that `?orderby=modified` does not work and was therefore redundant.

2022-09-08 06:37 UTC, mstokericatt approved these changes

2022-09-08 11:35 UTC, mstokericatt requested changes

2022-09-08 11:35 UTC, mstokericatt commented on src/features/werkbericht/WerkBericht.vue
> +  toggleReadIsLoading.value = false;
als readBericht of unreadBericht fout gaat kom je hier niet meer. Een foutmelding tonen heeft hiervoor misschien niet veel zin(even overleggen met sytske?), maar ik zou errors wel afvangen en toggleReadIsLoading en read.value weer goed zetten

2022-09-08 11:35 UTC, mstokericatt commented on src/features/werkbericht/service.ts
> +    console.log({ berichten });
beetje muggenziften, maar deze kan weg

2022-09-08 13:48 UTC, mstokericatt approved these changes

2022-09-08 13:48 UTC, mstokericatt commented on src/features/werkbericht/WerkBericht.vue
> +  toggleReadIsLoading.value = false;
prima. tip voor volgende stories: kijk even naar het gebruik van het ServiceResult object. die wordt op een aantal plekken gebruikt bij het ophalen van data en heeft als voordeel dat je niet zelf variabelen zoals toggleReadError hoeft bij te houden

2022-09-08 13:55 UTC, merged