Pc-309-AnoniemContactmomentOpslaan
Klantinteractie-Servicesysteem/KISS-frontend pull request #867
Opened 2024-08-29 09:30 UTC by githubjimmeicatt

2024-08-29 09:32 UTC, githubjimmeicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +
ik die iets van 4 calls, dus misschien kijken na welke calls we logging toevoegen?

actorcheck, actoraanmaak, contactmomentenaanmaak, actor contactmoment koppelen

2024-09-02 15:30 UTC, felixcicatt requested changes
Ik zie nog wel een aantal verbetermogelijkheden. Laten we morgen even overleggen.

2024-09-02 15:30 UTC, felixcicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +            return new ProxyResult(() =>
Zie andere comments. Ik denk niet dat dit een response is die we naar de client willen terugsturen. Je kan wat mij betreft de call doen en dan checken of de response een Ok status code heeft.

2024-09-02 15:30 UTC, felixcicatt commented on src/features/contact/contactmoment/types.ts
> +  shouldContinueWithContactmomenten?: boolean;
volgens mij wordt deze property nooit gevuld / gebruikt

2024-09-02 15:30 UTC, felixcicatt commented on Kiss.Bff.Test/PostKlantContactenCustomProxyTests.cs
> +        {
Dit ziet er best ingewikkeld uit. Heb je de library overwogen die we elders ook gebruiken?
https://github.com/richardszalay/mockhttp

2024-09-02 15:30 UTC, felixcicatt commented on Kiss.Bff.Test/PostKlantContactenCustomProxyTests.cs
> +            var clientHandlerStub = new DelegatingHandlerStub((request, cancellationToken) =>
wordt al deze logica overal gebruikt? is het misschien netter om per test alleen te mocken wat nodig is?

2024-09-03 08:05 UTC, felixcicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +    // Interface voor unittests en misschien zoiets lokaal implementeren?
Voorbeeld van hoe het zou kunnen: zie PostInterneTaakCustomProxy en InterneTaakProxyConfig

2024-09-03 08:12 UTC, felixcicatt commented on src/features/contact/contactmoment/service.ts
> +      errorMessage: responseBody.invalidParams
Verwachten we 400 meldingen waar we de melding van willen doorzetten naar de eindgebruiker?

2024-09-03 08:13 UTC, felixcicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +                parsedModel["medewerkerIdentificatie"] = _getMedewerkerIdentificatie();
volgens mij is dit niet nodig

2024-09-04 10:51 UTC, felixcicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +        public async Task<IActionResult> PostActoren()
Deze is nog relevant

2024-09-04 10:53 UTC, githubjimmeicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +        public async Task<IActionResult> PostActoren()
ja had ik net veranderd

2024-09-04 10:56 UTC, felixcicatt commented on Kiss.Bff/Extern/ZaakGerichtWerken/Contactmomenten/PostKlantcontactenCustomProxy.cs
> +        public async Task<IActionResult> LinkActorWithKlantContact(string actorUuid, string klantcontactUuid)
Hier hoef je geen IActionResult terug te geven. Je kan hier gewoon response.EnsureSuccessStatusCode() doen en een Task retourneren.

2024-09-04 11:02 UTC, felixcicatt commented on src/features/contact/contactmoment/service.ts
> +export function koppelBetrokkenen({
Beetje muggenzifterij misschien, maar: ik zou hier `koppelBetrokkene` van maken

2024-09-04 12:03 UTC, felixcicatt approved these changes

2024-09-04 12:08 UTC, merged